local Lib = {}
function Lib:CreateWindow(tText)
    local sg = Instance.new("ScreenGui") sg.Name = "KyyPremiumUI"
    pcall(function() sg.Parent = game:GetService("CoreGui") end)
    if not sg.Parent then sg.Parent = game:GetService("Players").LocalPlayer:WaitForChild("PlayerGui") end
    local mf = Instance.new("Frame") mf.Size = UDim2.new(0, 460, 0, 280) mf.Position = UDim2.new(0.5, -230, 0.5, -140) mf.BackgroundColor3 = Color3.fromRGB(15, 15, 20) mf.Active = true mf.Draggable = true mf.Parent = sg
    local st = Instance.new("UIStroke") st.Thickness = 2 st.ApplyStrokeMode = Enum.ApplyStrokeMode.Border st.Parent = mf
    Title = Instance.new("TextLabel") Title.Size = UDim2.new(1, 0, 0, 45) Title.BackgroundColor3 = Color3.fromRGB(24, 24, 30) Title.Text = "   " .. (tText or "PREMIUM HUB") Title.TextColor3 = Color3.fromRGB(255, 255, 255) Title.TextSize = 15 Title.TextXAlignment = Enum.TextXAlignment.Left Title.Font = Enum.Font.GothamBold Title.Parent = mf
    local tg = Instance.new("UIGradient") tg.Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(45, 120, 255)), ColorSequenceKeypoint.new(1, Color3.fromRGB(150, 45, 255))}) tg.Parent = Title
    local cm = Instance.new("TextButton") cm.Size = UDim2.new(0, 28, 0, 28) cm.Position = UDim2.new(1, -38, 0, 8) cm.BackgroundColor3 = Color3.fromRGB(35, 35, 45) cm.Text = "−" cm.TextColor3 = Color3.fromRGB(255, 255, 255) cm.Font = Enum.Font.GothamBold cm.Parent = mf
    OpenButton = Instance.new("TextButton") OpenButton.Size = UDim2.new(0, 50, 0, 50) OpenButton.Position = UDim2.new(0, 20, 1, -70) OpenButton.BackgroundColor3 = Color3.fromRGB(45, 120, 255) OpenButton.Text = "OPEN" OpenButton.TextColor3 = Color3.fromRGB(255, 255, 255) OpenButton.TextSize = 12 OpenButton.Font = Enum.Font.GothamBold OpenButton.Visible = false OpenButton.Parent = sg
    local os = Instance.new("UIStroke") os.Thickness = 2 os.Parent = OpenButton
    cm.MouseButton1Click:Connect(function() mf.Visible = false OpenButton.Visible = true end)
    OpenButton.MouseButton1Click:Connect(function() mf.Visible = true OpenButton.Visible = false end)
    local sb = Instance.new("Frame") sb.Size = UDim2.new(0, 120, 1, -45) sb.Position = UDim2.new(0, 0, 0, 45) sb.BackgroundColor3 = Color3.fromRGB(20, 20, 26) sb.Parent = mf
    local sl = Instance.new("UIListLayout") sl.Padding = UDim.new(0, 5) sl.HorizontalAlignment = Enum.HorizontalAlignment.Center sl.Parent = sb
    local cc = Instance.new("Frame") cc.Size = UDim2.new(1, -135, 1, -55) cc.Position = UDim2.new(0, 125, 0, 50) cc.BackgroundTransparency = 1 cc.Parent = mf
    task.spawn(function() local h = 0 while task.wait(0.01) do h = h + 0.004 if h > 1 then h = 0 end local r = Color3.fromHSV(h, 0.85, 0.85) if st then st.Color = r end if os then os.Color = r end end end)
    local tc = 0 local tbs = {} local lm = {}
    function lm:CreateTab(tName)
        tc = tc + 1
        local tContent = Instance.new("ScrollingFrame") tContent.Size = UDim2.new(1, 0, 1, 0) tContent.BackgroundTransparency = 1 tContent.ScrollBarThickness = 4 tContent.Visible = (tc == 1) tContent.AutomaticCanvasSize = Enum.AutomaticSize.Y tContent.CanvasSize = UDim2.new(0,0,0,0) tContent.Parent = cc
        local cl = Instance.new("UIListLayout") cl.Padding = UDim.new(0, 8) cl.Parent = tContent
        local btn = Instance.new("TextButton") btn.Size = UDim2.new(0, 110, 0, 36) btn.BackgroundColor3 = (tc == 1) and Color3.fromRGB(35, 40, 55) or Color3.fromRGB(26, 26, 34) btn.Text = tName btn.TextColor3 = Color3.fromRGB(255, 255, 255) btn.Font = Enum.Font.GothamBold btn.Parent = sb
        local bst = Instance.new("UIStroke") bst.Color = (tc == 1) and Color3.fromRGB(45, 120, 255) or Color3.fromRGB(40, 40, 50) bst.Parent = btn
        table.insert(tbs, {Button = btn, Content = tContent, Stroke = bst})
        btn.MouseButton1Click:Connect(function() for _, t in pairs(tbs) do t.Content.Visible = (t.Button == btn) t.Button.BackgroundColor3 = (t.Button == btn) and Color3.fromRGB(35, 40, 55) or Color3.fromRGB(26, 26, 34) t.Stroke.Color = (t.Button == btn) and Color3.fromRGB(45, 120, 255) or Color3.fromRGB(40, 40, 50) end end)
        local tm = {}
        function tm:CreateToggle(cfg)
            local toggleName = cfg.Name or "Toggle" local cb = cfg.Callback or function() end local isT = cfg.CurrentValue or false
            local tf = Instance.new("Frame") tf.Size = UDim2.new(1, -5, 0, 45) tf.BackgroundColor3 = Color3.fromRGB(24, 24, 32) tf.Parent = tContent
            local tt = Instance.new("TextLabel") tt.Size = UDim2.new(1, -70, 1, 0) tt.Position = UDim2.new(0, 10, 0, 0) tt.BackgroundTransparency = 1 tt.Text = toggleName tt.TextColor3 = Color3.fromRGB(240, 240, 245) tt.TextSize = 12 tt.TextXAlignment = Enum.TextXAlignment.Left tt.Font = Enum.Font.GothamBold tt.Parent = tf
            local sBg = Instance.new("Frame") sBg.Size = UDim2.new(0, 46, 0, 22) sBg.Position = UDim2.new(1, -56, 0.5, -11) sBg.BackgroundColor3 = isT and Color3.fromRGB(46, 204, 113) or Color3.fromRGB(50, 50, 60) sBg.Parent = tf
            local sc = Instance.new("UICorner") sc.CornerRadius = UDim.new(0, 11) sc.Parent = sBg
            local cir = Instance.new("Frame") cir.Size = UDim2.new(0, 16, 0, 16) cir.Position = isT and UDim2.new(1, -19, 0.5, -8) or UDim2.new(0, 3, 0.5, -8) cir.BackgroundColor3 = Color3.fromRGB(255, 255, 255) cir.Parent = sBg
            local ccir = Instance.new("UICorner") ccir.CornerRadius = UDim.new(0, 8) ccir.Parent = cir
            local hb = Instance.new("TextButton") hb.Size = UDim2.new(1, 0, 1, 0) hb.BackgroundTransparency = 1 hb.Text = "" hb.Parent = sBg
            hb.MouseButton1Click:Connect(function() isT = not isT
                if isT then sBg.BackgroundColor3 = Color3.fromRGB(46, 204, 113) cir:TweenPosition(UDim2.new(1, -19, 0.5, -8), "Out", "Quad", 0.12, true) else sBg.BackgroundColor3 = Color3.fromRGB(50, 50, 60) cir:TweenPosition(UDim2.new(0, 3, 0.5, -8), "Out", "Quad", 0.12, true) end cb(isT)
            end)
        end return tm
    end return lm
end

local pS = game:GetService("Players") local lp = pS.LocalPlayer local vU = game:GetService("VirtualUser") local vI = game:GetService("VirtualInputManager") local gS = game:GetService("GuiService")
task.spawn(function() while true do task.wait(0.5) if _G.AutoFarm then local char = lp.Character if not char or (char:FindFirstChild("Humanoid") and char.Humanoid.Health <= 0) then local pGui = lp:FindFirstChild("PlayerGui") if pGui then for _, g in pairs(pGui:GetDescendants()) do if g:IsA("TextButton") then local bT = string.gsub(g.Text, "%s+", "") if string.lower(bT) == "spawn" and g.AbsoluteSize.X > 0 then pcall(function() g:Activate() local pX = g.AbsolutePosition.X + (g.AbsoluteSize.X / 2) local pY = g.AbsolutePosition.Y + (g.AbsoluteSize.Y / 2) + gS:GetGuiInset().Y vI:SendMouseButtonEvent(pX, pY, 0, true, game, 1) task.wait(0.05) vI:SendMouseButtonEvent(pX, pY, 0, false, game, 1) if getconnections then for _, c in pairs(getconnections(g.MouseButton1Click)) do c:Fire() end for _, c in pairs(getconnections(g.MouseButton1Down)) do c:Fire() end end end) end end end end end end end end)
local Menu = lm or Lib:CreateWindow("Kyyuuunopro Cyber Hub v3 🚀")
local tab1 = Menu:CreateTab("Farm Mobs ⚔️") local tab2 = Menu:CreateTab("Teleport Đảo 🌀") local tab3 = Menu:CreateTab("Compass 🧭")
local _G = _G or {} _G.AutoFarm = false _G.AutoPickCompass = false _G.AutoFlyToCompassDirection = false
local fMBL = {} local cT = nil local pH = 0 local cTim = 0 local tNPCs = {"Bandit", "Thug", "Angry bob", "Angry Freddy", "Thief", "Gunslinger"}
local function isNPC(n) local ln = string.lower(n) for _, t in pairs(tNPCs) do if string.find(ln, string.lower(t)) then return true end end return false end

tab1:CreateToggle({Name = "Auto Farm Mobs (Máu < 1000)", CurrentValue = false, Callback = function(v) _G.AutoFarm = v if _G.AutoFarm then fMBL = {} cT = nil cTim = 0 task.spawn(function() while _G.AutoFarm do task.wait(0.02) local char = lp.Character if char then local mr = char:FindFirstChild("HumanoidRootPart") local mh = char:FindFirstChildOfClass("Humanoid") if mr and mh and mh.Health > 0 then local tN = nil local tP = nil for _, o in pairs(workspace:GetDescendants()) do if not fMBL[o] then local eh = o:FindFirstChildOfClass("Humanoid") if eh and eh.Health > 0 and eh.MaxHealth < 1000 then local isP = pS:GetPlayerFromCharacter(o) if not isP and o.Name ~= lp.Name then if isNPC(o.Name) or o.Name == "" or o.Name == "NPC" or string.len(o.Name) <= 4 or o:IsA("Model") then local isQ = false local cP = o.Parent while cP and cP ~= workspace do local pN = string.lower(cP.Name) if string.find(pN, "quest") or string.find(pN, "giver") or string.find(pN, "dialog") then isQ = true break end cP = cP.Parent end if not isQ then local p = o:FindFirstChild("HumanoidRootPart") or o:FindFirstChild("Torso") or o:FindFirstChild("Head") or o:FindFirstChild("Base") or o:FindFirstChildOfClass("Part") if p then tN = o tP = p break end end end end end end end if tN and tP then local eh = tN:FindFirstChildOfClass("Humanoid") if cT == tN then if eh and eh.Health >= pH then cTim = cTim + 1 if cTim > 25 then fMBL[tN] = true cT = nil cTim = 0 end else if eh then pH = eh.Health end cTim = 0 end else cT = tN if eh then pH = eh.Health end cTim = 0 end if cT == tN and not fMBL[tN] then mr.CFrame = CFrame.new(tP.Position + (tP.CFrame.LookVector * -1.2), tP.Position) local tl = char:FindFirstChildOfClass("Tool") if not tl then local bpt = lp.Backpack:FindFirstChildOfClass("Tool") if bpt then bpt.Parent = char end end pcall(function() vU:CaptureController() vU:ClickButton1(Vector2.new(9999, 9999)) end) end end end end end end end) end end})
local function tpIs(iName) if lp.Character and lp.Character:FindFirstChild("HumanoidRootPart") then local mr = lp.Character.HumanoidRootPart local fI = nil for _, o in pairs(workspace:GetDescendants()) do if string.find(string.lower(o.Name), string.lower(iName)) and (o:IsA("BasePart") or o:IsA("Model")) then fI = o break end end if fI then local ic if fI:IsA("Model") then ic = fI:GetBoundingBox() else ic = fI.CFrame end mr.Anchored = true mr.CFrame = ic * CFrame.new(0, 120, 0) task.wait(1.5) mr.Anchored = false end end end
tab2:CreateToggle({Name = "Dịch chuyển đến Đảo Tân Thủ", CurrentValue = false, Callback = function(v) if v then tpIs("Starter Island") end end})
tab2:CreateToggle({Name = "Dịch chuyển đến Đảo Hải Tặc", CurrentValue = false, Callback = function(v) if v then tpIs("Pirate Island") end end})
tab2:CreateToggle({Name = "Dịch chuyển đến Đảo Hải Quân", CurrentValue = false, Callback = function(v) if v then tpIs("Marine Base") end end})

local lastD = Vector3.new(0,0,0) local sTim = 0
tab3:CreateToggle({Name = "Teleport nhặt Compass rơi trên đất", CurrentValue = false, Callback = function(v) _G.AutoPickCompass = v if _G.AutoPickCompass then task.spawn(function() while _G.AutoPickCompass do task.wait(0.1) local char = lp.Character if char and char:FindFirstChild("HumanoidRootPart") then local mr = char.HumanoidRootPart local tC = nil for _, o in pairs(workspace:GetDescendants()) do if string.find(string.lower(o.Name), "compass") then if o:IsA("Tool") and o:FindFirstChild("Handle") then tC = o.Handle break elseif o:IsA("BasePart") and not o:IsAncestorOf(char) then tC = o break end end end if tC then mr.Anchored = true mr.CFrame = tC.CFrame * CFrame.new(0, 2, 0) task.wait(0.2) mr.Anchored = false end end end end) end end})
tab3:CreateToggle({Name = "Bay theo hướng la bàn chỉ", CurrentValue = false, Callback = function(v) _G.AutoFlyToCompassDirection = v if _G.AutoFlyToCompassDirection then lastD = Vector3.new(0,0,0) sTim = 0 task.spawn(function() while _G.AutoFlyToCompassDirection do task.wait(0.01) local char = lp.Character if char and char:FindFirstChild("HumanoidRootPart") then local mr = char.HumanoidRootPart local bpc = lp.Backpack:FindFirstChild("Compass") if bpc then bpc.Parent = char end local hc = char:FindFirstChild("Compass") if hc then pcall(function() hc:Activate() end) local nd = hc:FindFirstChild("Needle") or hc:FindFirstChild("Pointer") or hc:FindFirstChild("Arrow") or hc:FindFirstChild("Handle") or hc:FindFirstChildOfClass("MeshPart") or hc:FindFirstChildOfClass("Part") local rd = nd and nd.CFrame.LookVector or mr.CFrame.LookVector local fd = Vector3.new(rd.X, 0, rd.Z).Unit local aC = math.acos(math.clamp(lastD:Dot(fd), -1, 1)) if aC > math.rad(90) and lastD.Magnitude > 0 then sTim = sTim + 1 if sTim > 10 then mr.Anchored = false for i = 1, 30 do task.wait(0.05) pcall(function() vU:CaptureController() vU:ClickButton1(Vector2.new(9999, 9999)) end) end sTim = 0 mr.CFrame = CFrame.new(mr.Position.X, 70, MyPos or mr.Position.Z) end else sTim = 0 mr.Anchored = true local np = mr.Position + (fd * 12) mr.CFrame = CFrame.new(Vector3.new(np.X, 70, np.Z), Vector3.new(np.X + fd.X, 70, np.Z + fd.Z)) end lastD = fd else mr.Anchored = false end end end if lp.Character and lp.Character:FindFirstChild("HumanoidRootPart") then lp.Character.HumanoidRootPart.Anchored = false end end end) else if lp.Character and lp.Character:FindFirstChild("HumanoidRootPart") then lp.Character.HumanoidRootPart.Anchored = false end end end})
